name: CI

on:
  push:
    branches: [ main, master, trunk, develop ]
    tags: [ 'v*.*.*' ]
  pull_request:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.25.x' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go Vet
        run: go vet ./...

      - name: Build (HTTP + MCP)
        run: |
          go build -v -ldflags "-s -w -X github.com/aknarts/chef-server-mcp/internal/version.Version=${{ github.sha }}" -o chef-mcp ./cmd/chef-mcp
          go build -v -ldflags "-s -w -X github.com/aknarts/chef-server-mcp/internal/version.Version=${{ github.sha }}" -o mcp-chef ./cmd/mcp-chef

      - name: Tests
        run: go test -race -coverprofile=coverage.out ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Build Docker image (no push)
        run: |
          docker build --build-arg VERSION=${{ github.sha }} -t local/chef-mcp:${{ github.sha }} .

  docker-publish:
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

      - name: Build release binaries
        run: |
          go build -ldflags "-s -w -X github.com/aknarts/chef-server-mcp/internal/version.Version=${{ github.ref_name }}" -o chef-mcp ./cmd/chef-mcp
          go build -ldflags "-s -w -X github.com/aknarts/chef-server-mcp/internal/version.Version=${{ github.ref_name }}" -o mcp-chef ./cmd/mcp-chef
          tar -czf chef-mcp_${{ github.ref_name }}_linux_amd64.tar.gz chef-mcp
          tar -czf mcp-chef_${{ github.ref_name }}_linux_amd64.tar.gz mcp-chef
        shell: bash
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: |
            chef-mcp_*_linux_amd64.tar.gz
            mcp-chef_*_linux_amd64.tar.gz
